defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 55
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *defaults
  database: exodus_development

test:
  <<: *defaults
  database: exodus_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: 127.0.0.1
  port: 3306
